blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.home_page, name='home'),
    path('blog/', views.PostList.as_view(), name='blog'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
    path('like/<slug:slug>', views.PostLike.as_view(), name='post_like'),
]

shoes/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('shoess/', views.ShoessPage.as_view(), name='shoess'),
    path('submitshoes/', views.submit_shoes, name='submit_shoe'),
    path('edit/<slug:slug>', views.edit_shoes, name='edit_shoe'),
    path('delete/<slug:slug>', views.delete_shoes, name='delete_shoe'),
    path('<slug:slug>/', views.ShoesDetails.as_view(), name='shoes_detail'),
    path('like/<slug:slug>', views.LikeShoePair.as_view(), name='like_shoe'),
]

thewalkingshoes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'), name='blog_urls'),
    path('shoes/', include('shoes.urls'), name='shoes_urls'),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('allauth.urls')),
    
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

STATUS = ((0, "Draft"), (1, "Published"))

class Post (models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="blog_posts")
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    featured_image = CloudinaryField('image', default='placeholder')
    excerpt = models.TextField(blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(User, related_name='blog_likes', blank=True)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title

    def number_of_likes(self):
        return self.likes.count()

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.name}"

shoes/models.py
# models for Shoes trading app
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.template.defaultfilters import slugify


STATUS = ((0, "Draft"), (1, "Published"))


class Category(models.Model):
    #Shoe Categories
    categories = models.CharField(max_length=20)

    class Meta:
        #Display Trade
        ordering = ("categories",)

    def __str__(self):
        #Display Trade
        return self.categories


class ShoePair(models.Model):
    #model for trading shoes
    shoe_name = models.CharField(
        max_length=50, unique=True, null=False, blank=False)
    slug = models.SlugField(
        max_length=50, unique=True, null=False, blank=False)
    trader = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='shoe_pair')
    description = models.TextField()
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT, blank=False, null=False)
    shoe_image = CloudinaryField('image', null=False, blank=False)
    shoe_size = models.IntegerField(null=False, blank=False)
    status = models.IntegerField(choices=STATUS, default=0)
    remaining_pairs = models.IntegerField(null=False, blank=False)
    price = models.IntegerField(null=False, blank=False)
    likes = models.ManyToManyField(User, related_name='shoe_likes', blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    amount_of_pairs = models.IntegerField(null=False, blank=False)

    class Meta:
        #display shoes in most recent order
        ordering = ['-created_on']

    def __str__(self):
        #Display Shoe type
        return f'{self.shoe_name}'

    #auto generate slug fields
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.shoe_name)
        return super().save(*args, **kwargs)

    def number_of_likes(self):
        #Return number of likes per shoes
        return self.likes.count()

blog/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

shoes/forms.py
from django import forms
from .models import ShoePair


class SubmitShoesForm(forms.ModelForm):
    #Shoe submission form
    class Meta:
        #generate fields for submission
        model = ShoePair
        fields = (
            'shoe_name',
            #'slug',
            'description',
            'category',
            'shoe_image',
            'shoe_size',
            'amount_of_pairs',
            'remaining_pairs',
            'price',
        )
        labels = {
            'shoe_name': 'Shoe name',
            #'slug': 'Repeat name. Do not include spaces.',
            'description': 'Description',
            'category': 'Category',
            'shoe_image': 'Select image',
            'shoe_size': 'Shoe size in UK sizes',
            'amount_of_pairs': "Number of pairs at launch",
            'remaining_pairs': "How many pairs remaining",
            'price': 'Price in Euros',
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic, View
from django.http import HttpResponseRedirect
from .models import Post
from .forms import CommentForm

def home_page(request):
    """
    View for home page.
    """
    return render(request, 'index.html')

class PostList(generic.ListView):
    model = Post
    queryset = Post.objects.filter(status=1).order_by("-created_on")
    template_name = "blog.html"
    paginate_by = 6


class PostDetail(View):

    def get(self, request, slug, *args, **kwargs):
        queryset = Post.objects.filter(status=1)
        post = get_object_or_404(queryset, slug=slug)
        comments = post.comments.filter(approved=True).order_by("-created_on")
        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            "post_detail.html",
            {
                "post": post,
                "comments": comments,
                "commented": False,
                "liked": liked,
                "comment_form": CommentForm()
            },
        )
    
    def post(self, request, slug, *args, **kwargs):

        queryset = Post.objects.filter(status=1)
        post = get_object_or_404(queryset, slug=slug)
        comments = post.comments.filter(approved=True).order_by("-created_on")
        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True

        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.save()
        else:
            comment_form = CommentForm()

        return render(
            request,
            "post_detail.html",
            {
                "post": post,
                "comments": comments,
                "commented": True,
                "comment_form": comment_form,
                "liked": liked
            },
        )

class PostLike(View):
    
    def post(self, request, slug, *args, **kwargs):
        post = get_object_or_404(Post, slug=slug)
        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
        else:
            post.likes.add(request.user)

        return HttpResponseRedirect(reverse('post_detail', args=[slug]))

shoes/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.views import generic, View
from django.http import HttpResponseRedirect
from django.contrib import messages
from .models import ShoePair
from .forms import SubmitShoesForm


class ShoessPage(generic.ListView):
    #View ShoessPage
    model = ShoePair
    queryset = ShoePair.objects.filter(status=1).order_by('-created_on')
    template_name = 'shoess.html'
    paginate_by = 8


def submit_shoes(request):
    #View for shoes submission page
    if request.method == 'POST':
        submission_form = SubmitShoesForm(request.POST, request.FILES)
        if submission_form.is_valid():
            submission_form.instance.trader = request.user
            submission_form.save()
            messages.success(
                request, "Submission has been successfull.Your trade will show up on our page as soon as it has been reviewed")
            return redirect('shoess')
        else:
            submission_form = SubmitShoesForm()

    return render(
        request,
        'submit-shoes.html',
        {
            'submission_form': SubmitShoesForm(),
        },
    )


def edit_shoes(request, slug):
    #Edit submitted trade
    shoess = get_object_or_404(ShoePair, slug=slug)
    edit_form = SubmitShoesForm(request.POST or None, instance=shoess)
    context = {
        'edit_form': edit_form,
        'shoess': shoess
    }

    if request.method == 'POST':
        edit_form = SubmitShoesForm(
            request.POST, request.FILES, instance=shoess)
        if edit_form.is_valid():
            shoess = edit_form.save(commit=False)
            shoess.trader = request.user
            shoess.save()
            return redirect('shoess')
    else:
        edit_form = SubmitShoesForm(instance=shoess)

    return render(request, 'edit-shoes.html', context)


def delete_shoes(request, slug):
    #Delete submitted shoes
    shoess = get_object_or_404(ShoePair, slug=slug)
    shoess.delete()
    return redirect('shoess')


class ShoesDetails(View):
    # Render shoes to site
    def get(self, request, slug, *args, **kwargs):
        #Obtain print & check for likes.
        queryset = ShoePair.objects.filter(status=1)
        shoess = get_object_or_404(queryset, slug=slug)
        liked = False
        if shoess.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            'shoes-details.html',
            {
                'shoess': shoess,
                'liked': liked,
            }
        )


# Class used from "I think therefore I blog" walkthrough.
class LikeShoePair(View):
    #let users like shoe submitions
    def post(self, request, slug):
        #Check if user likes posts
        shoess = get_object_or_404(ShoePair, slug=slug)
        if shoess.likes.filter(id=request.user.id).exists():
            shoess.likes.remove(request.user)
        else:
            shoess.likes.add(request.user)
        return HttpResponseRedirect(reverse('shoes_detail', args=[slug]))

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>TheWalkingShoes</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Let you trade your shoes with other shoe fanatics.">
    <meta name="keywords" content="Shoes, Blog, Trading">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        type="text/css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body class="d-flex flex-column h-100 main-bg">

    <!-- Header -->
    <header>

        <!-- Navbar Burgermenu/ Mobile view -->
        <div class="dropdown-center display-mobile menu-btn-container">
            <div class="logo_mobile">
                <a class="list-inline-item logo-mobile" href="{% url 'home' %}" class="nav-bar logo">TheWalking<span class="walking">Shoes</span></a>
            </div>

                <button class="btn btn-secondary dropdown-toggle menu-btn" type="button" id="dropdownCenterBtn" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fa-solid fa-bars"></i>
                </button>

                <ul class="dropdown-menu" aria-labelledby="dropdownCenterBtn">
                    <li>
                        <a href="{% url 'home' %}" class="nav-bar">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'shoess' %}" class="nav-bar">Shoes</a>
                    </li>
                    <li>
                        <a href="{% url 'blog' %}" class="nav-bar">Blog</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <a class="nav-bar" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li>
                        <a class="nav-bar" href="{% url 'account_login' %}">Login / Sign up</a>
                    </li>
                    {% endif %}
                </ul>
          </div>

        <!-- NAVIGATION BAR -->
        <nav class="row remove-mobile">
            <div class="col navbar">
                <ul id="nav" class="list-inline">
                    <li class="list-inline-item">
                        <a href="{% url 'home' %}" class="nav-bar logo">TheWalking<span class="walking">Shoes</span></a>
                    </li>
                    <li class="list-inline-item">
                        <a href="{% url 'home' %}" class="nav-bar">Home</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="{% url 'shoess' %}" class="nav-bar">Shoes</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="{% url 'blog' %}" class="nav-bar">Blog</a>
                    </li>
                    <!-- taken from "I think therefore I blog" -->
                    {% if user.is_authenticated %}
                    <li class="list-inline-item">
                        <a class="nav-bar" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="list-inline-item">
                        <a class="nav-bar" href="{% url 'account_login' %}">Login / Sign up</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <main class="flex-shrink-0 main-bg">
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3">
        <div class="row">
            <ul id="social" class="list-inline">
                <li class="list-inline-item social-icon">
                    <a href="https://facebook.com" target="_blank" rel="noopener"
                        aria-label="Visit our Facebook page (opens in a new tab)">
                        <i class="fa-brands fa-facebook-f"></i>
                    </a>
                </li>
                <li class="list-inline-item social-icon">
                    <a href="https://discord.com" target="_blank" rel="noopener"
                        aria-label="Visit our discord page (opens in a new tab)">
                        <i class="fa-brands fa-discord"></i>
                    </a>
                </li>
            </ul>
        </div>
    </footer>

    <script src="https://kit.fontawesome.com/517da91cea.js" crossorigin="anonymous"></script>

    <script>
        setTimeout(function () {
            let messages = document.getElementById('msg');
            let alert = new bootstrap.Alert(messages);
            alert.close();
        }, 2500);
    </script>
</body>

</html>

templates/blog.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">
    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-12 left">
            <div class="row">
                {% for post in post_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in post.featured_image.url %}
                                <img class="card-img-top"
                                    src="/static/images/edgar.jpg">
                                {% else %}
                                <img class="card-img-top" src=" {{ post.featured_image.url }}">
                                {% endif %}
                                <div class="image-flash">
                                    <p class="author">Author: {{ post.author }}</p>
                                </div>
                                <hr class="line-hr">
                            </div>
                            <a href="{% url 'post_detail' post.slug %}" class="post-link">
                                <h3 class="card-title post-title">{{ post.title }}</h3>
                                <p class="card-text">{{ post.excerpt }}</p>
                            </a>
                            
                            <p class="card-text date-text">{{ post.created_on }}</p>
                            <p><i class="far fa-heart"></i>{{ post.number_of_likes }}</p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{%endblock%}

templates/edit-shoes.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
{% load cloudinary %}

<div class="col-12 shoes-container">
    <div class="row submission-form">
    <!-- Submission Field -->
        {% if user.is_authenticated %}
        <div class="col-sm-6 c">
            <div class="card mb-4">
                <div class="card-body all-trading-posts">
                    <h2>Edit your Shoes:</h2>
                    <hr />
                    <form method="POST" style="margin-top: 1.3em;" enctype="multipart/form-data">
                        {{ edit_form | crispy }}
                        {% csrf_token %}
                        <button type="submit" class="submit-shoe-btn">Submit Changes</button>
                    </form>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>

{%endblock%}

templates/index.html
{% extends "base.html" %}

{% block content %}

{% load static %}

<div class="col home-page">
    <div class="row">
        <div class="col-md-8 home-image">
            <img src="{% static 'images/shoecircle.jpg' %}" alt="shoecircle">
        </div>
        <div class="col-md-4 home-paragraph">
            <h3 class="about-us">About us: </h3>
            <p>Welcome to TheWalking<span class="greenspan">SHOES</span></p>
            <br>
            <p>TheWalking<span class="greenspan">SHOES</span> is a platform for shoe lovers where they get the chance
                to trade shoes with other people "traders" as we call them.
            </p>
            <p>This concepts originate from the idea of over consumption and we think this
                could be a more affordable option than buy new shoes. 
            </p>
            <p>If you have a pair of shoes thats you just worn once or twice and just collecting dust in the 
                wardrobe look no further. Post your shoes on our <a class="link" href="{% url 'shoess' %}">Shoes</a> and 
                find someone you can trade them with you. You get a new pair and your old pair gets a new home.
                You will be contacted via discord by a trader for a safe semi anonymous trade.
            </p>
        </div>
    </div>
</div>

{% endblock %}

templates/post_detail.html
{% extends 'base.html' %} 
{% block content %}
{% load crispy_forms_tags %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <!-- Post title goes in these h1 tags -->
                <h3 class="post-title">{{ post.title }}</h3>
                <!-- Post author goes before the | the post's created date goes after -->
                <p class="post-subtitle">{{ post.author }} | {{ post.created_on }}</p>
            </div>
            <div class="d-none d-md-block col-md-6 masthead-image">
                <!-- The featured image URL goes in the src attribute -->
                {% if "placeholder" in post.featured_image.url %}
                <img class="manyshoes-size"src="/static/images/manyshoes.jpg">
                {% else %}
                <img src=" {{ post.featured_image.url }}" width="100%">
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col card mb-4  mt-3 left  top">
            <div class="card-body">
                <!-- The post content goes inside the card-text. -->
                <!-- Use the | safe filter inside the template tags -->
                <p class="card-text ">
                    {{ post.content | safe }}
                </p>
                <div class="row">

                    <div class="col-1">
                        <strong>
                            {% if user.is_authenticated %}
                            <form class="d-inline" action="{% url 'post_like' post.slug %}" method="POST">
                                {% csrf_token %}
                                {% if liked %}
                                <button type="submit" name="blogpost_id" value="{{post.slug}}" class="btn-like"><i class="fas fa-heart"></i></button>
                                {% else %}
                                <button type="submit" name="blogpost_id" value="{{post.slug}}" class="btn-like"><i class="far fa-heart"></i></button>
                                {% endif %}
                            </form>
                            {% else %}
                            <span class="text-secondary"><i class="far fa-heart"></i></span>
                            {% endif %}
                        <!-- The number of likes goes before the closing strong tag -->
                        <span class="text-secondary">{{ post.number_of_likes }} </span>
                        </strong>
                    </div>
                    <div class="col-1">
                        {% with comments.count as total_comments %}
                        <strong class="text-secondary"><i class="far fa-comments"></i>
                            <!-- Our total_comments variable goes before the closing strong tag -->
                            {{ total_comments }}</strong>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 ">
            <h3>Comments:</h3>
            <div class="card-body">
                <!-- We want a for loop inside the empty control tags to iterate through each comment in comments -->
                {% for comment in comments %}
                <div class="comments" style="padding: 10px;">
                    <p class="font-weight-bold">
                        <!-- The commenter's name goes here. Check the model if you're not sure what that is -->
                        {{ comment.name }}
                        <span class=" text-muted font-weight-normal">
                            <!-- The comment's created date goes here -->
                            {{ comment.created_on }}
                        </span> wrote:
                    </p>
                    <!-- The body of the comment goes before the | -->
                    {{ comment.body | linebreaks }}
                </div>
                <!-- Our for loop ends here -->
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4 card mb-4  mt-3 ">
            <div class="card-body">
                <!-- For later -->
                {% if commented %}
                <div class="alert alert-success" role="alert">
                    Your comment is awaiting approval
                </div>
                {% else %}
                {% if user.is_authenticated %}

                <h3>Leave a comment:</h3>
                <p>Posting as: {{ user.username }}</p>
                <form method="post" style="margin-top: 1.3em;">
                    {{ comment_form | crispy }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-signup btn-lg">Submit</button>
                </form>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/shoess.html
{% extends 'base.html' %}

{% block content %}

<!-- Shoes -->
<div class="col-12 shoes-container">
    <div class="row display-shoes new-submission">
        <!-- Submission field -->
        {% if user.is_authenticated %}
        <div class="col-sm-6 submit-your-shoes">
            <div class="card mb-4 submit-your-shoes-box">
                <div class="card-body all-trading-posts">
                    <h2>Submit your Shoes:</h2>
                    <hr/>
                    <p>Got a pair of shoes you want to trade?</p>
                    <p>Click the button!</p>
                    <br>
                    <button onclick="location.href='{% url 'submit_shoe' %}'" type="button" class="submit-shoe-btn">SUBMIT SHOES</button>
                </div>
            </div>
        </div>
        {% endif %}
    </div>

    <div class="row display-shoes">
        <!-- Approved submissions -->
        {% for shoe in shoepair_list %}
        <div class="col-md-6 col-lg-3">
            <div class="card mb-4">
                <div class="card-body all-trading-posts">
                    <div class="image-container">
                        <img class="card-img-top" src="{{ shoe.shoe_image.url }}" alt="{{ shoe.shoe_name }}">
                        <div class="image-flash">
                            <p>Trader: {{ shoe.trader }}</p>
                        </div>
                    </div>
                    <a href="{% url 'shoes_detail' shoe.slug %}" class="shoe-link">
                        <h2>{{ shoe.shoe_name }}</h2>
                    </a>
                    <hr />
                    <p>Remaining pairs: {{ shoe.remaining_pairs }}/{{ shoe.amount_of_pairs }}</p>
                    <p>Price: €{{ shoe.price }}</p>
                    <p class="card-text date-text"><i class="far fa-heart"></i> {{ shoe.number_of_likes }}</p>
                </div>
            </div>
        </div>
        {% if forloop.counter|divisibleby:4 %}
    </div>
    <div class="row display-shoes">
        {% endif %}
        {% endfor %}
    </div>

    <br>

    <div class="row next-prev-button">
        {% if is_paginated %}
        <div class="next-prev">
            {% if page_obj.has_previous %}
            <button onclick="location.href='?page={{ page_obj.previous_page_number }}'" type="button" class="pagination-button">PREV</button>
            {% endif %}
            {% if page_obj.has_next %}
            <button onclick="location.href='?page={{ page_obj.next_page_number }}'" type="button" class="pagination-button">NEXT</button>
            {% endif %}
        </div>
    {% endif %}
    </div>
</div>

{%endblock%}

templates/submit-shoes.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
{% load cloudinary %}

<div class="col-12 shoes-container">
    <div class="row submission-form">
    <!-- Submission Field -->
        {% if user.is_authenticated %}
        <div class="col-sm-6 submit-block">
            <div class="card mb-4">
                <div class="card-body all-trading-posts">
                    <h2>Submit your Shoes:</h2>
                    <hr />
                    <p>Click the button</p>
                    <form method="POST" style="margin-top: 1.3em;" enctype="multipart/form-data">
                        {{ submission_form | crispy }}
                        {% csrf_token %}
                        <button type="submit" class="all-trading-posts submit-shoe-btn">Submit</button>
                    </form>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>

{%endblock%}